"""The README's status table, generated from the expected outcomes.

    pdm run acceptance-status [--check]

The table shows each tool group's tools by their fixture-mode outcome, which the per-tool report
derives from the outcomes of the tests (report.py); the tests' tools and gates are read from
the suite's markers, so the front page reports what the suite measures and not what someone last
wrote. It is written between two markers of the README. `--check` writes nothing and exits with
1 when the README is not current, and a self-test fails then as well.
"""

from __future__ import annotations

import argparse
import contextlib
import io
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import pytest

from nci_si_acceptance.expected import EXPECTED
from nci_si_acceptance.report import (
    FAIL,
    FAILED,
    INCOMPLETE,
    NO_FIXTURE,
    NO_TESTS,
    NOT_IMPLEMENTED,
    NOT_RUN,
    PASS,
    tool_outcome,
)
from nci_si_acceptance.spec import REQUIRED_TOOLS

ACCEPTANCE = EXPECTED.parents[1]
README = ACCEPTANCE.parent / "README.md"
BEGIN, END = "<!-- acceptance-status:begin -->", "<!-- acceptance-status:end -->"
GROUPS = {
    "evs": "EVS tools",
    "cadsr": "caDSR tools",
    "cross-domain": "Cross-domain tools",
    "workflow": "Workflow tools",
}
# The order a group's tools are listed in: best outcome first.
ORDER = (PASS, INCOMPLETE, NO_FIXTURE, FAIL, NOT_RUN, NOT_IMPLEMENTED, NO_TESTS)

Attribution = dict[str, tuple[str | None, bool]]


class _Marks:
    """A pytest plugin that notes the tool and gate markers of every test it collects."""

    def __init__(self) -> None:
        self.found: Attribution = {}

    def pytest_collection_modifyitems(self, items: list[pytest.Item]) -> None:
        for item in items:
            marker = item.get_closest_marker("tool")
            gate = item.get_closest_marker("gate") is not None
            self.found[item.nodeid] = (marker.args[0] if marker else None, gate)


def collect_attribution() -> Attribution:
    """The tool and gate of every test of the suite, by collecting it: no test runs."""

    marks = _Marks()
    arguments = [
        *("--collect-only", "-q", "-p", "no:cacheprovider"),
        *("-c", str(ACCEPTANCE / "pyproject.toml"), "--rootdir", str(ACCEPTANCE)),
        str(ACCEPTANCE / "tests"),
    ]
    with contextlib.redirect_stdout(io.StringIO()):
        status = pytest.main(arguments, plugins=[marks])
    if status:
        raise SystemExit(f"collecting the suite failed with exit status {status}")
    return marks.found


def tool_outcomes(expected: dict[str, str], attribution: Attribution) -> dict[str, str]:
    """The outcome of each required tool, by the rule of the per-tool report. No server has
    started, so a tool is taken as not implemented when every test of it was skipped for want
    of it."""

    failed_gates = any(
        gate and expected.get(nodeid) in FAILED for nodeid, (_, gate) in attribution.items()
    )
    outcomes = {}
    for name in REQUIRED_TOOLS:
        counts = Counter(
            expected[nodeid] for nodeid, (tool, _) in attribution.items() if tool == name
        )
        implemented = not (counts and set(counts) == {"not_implemented"})
        outcomes[name] = tool_outcome(counts, failed_gates, implemented)
    return outcomes


def _cell(outcome: str, names: list[str]) -> str:
    return f"{outcome}: " + ", ".join(f"`{name}`" for name in names)


def _listed(names: list[str], outcomes: dict[str, str]) -> dict[str, list[str]]:
    return {outcome: [n for n in names if outcomes[n] == outcome] for outcome in ORDER}


def _row(group: str, title: str, outcomes: dict[str, str]) -> str:
    names = [name for name, tool_group in REQUIRED_TOOLS.items() if tool_group == group]
    listed = _listed(names, outcomes)
    cells = [_cell(outcome, found) for outcome, found in listed.items() if found]
    return f"| {title} | {len(names)} | {'<br>'.join(cells)} |"


def render(expected: dict[str, str], attribution: Attribution) -> str:
    """The README's table: for each group, its tools listed under their outcome."""

    outcomes = tool_outcomes(expected, attribution)
    lines = [
        BEGIN,
        f"Fixture-mode outcome of each tool, from the expected outcomes of the {len(expected)} "
        "tests of the acceptance suite "
        "([acceptance/expected/fixture.json](acceptance/expected/fixture.json)); "
        "[acceptance/README.md](acceptance/README.md#the-report) defines the outcomes. "
        "This table is generated by `pdm run acceptance-status`.",
        "",
        "| Group | Tools | Outcome of each tool |",
        "|---|---|---|",
    ]
    lines += [_row(group, title, outcomes) for group, title in GROUPS.items()]
    return "\n".join([*lines, END])


def current(readme: str, table: str) -> str:
    """The README with the text between the markers replaced by `table`."""

    before, found, rest = readme.partition(BEGIN)
    _, end, after = rest.partition(END)
    if not (found and end):
        raise SystemExit(f"the README lacks the markers {BEGIN} and {END}")
    return before + table + after


def main(arguments: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Write the README's status table.")
    parser.add_argument("--check", action="store_true", help="write nothing; fail if not current")
    parser.add_argument("--readme", type=Path, default=README, help="the README to write")
    options = parser.parse_args(arguments)
    expected: dict[str, Any] = json.loads(EXPECTED.read_text(encoding="utf-8"))
    readme = options.readme.read_text(encoding="utf-8")
    attribution = collect_attribution()
    if stale := sorted(attribution.keys() ^ expected.keys()):
        raise SystemExit(
            f"the expected outcomes and the suite differ in {len(stale)} tests, among them "
            f"{stale[0]}; run the suite and pdm run acceptance-expected update"
        )
    written = current(readme, render(expected, attribution))
    if written == readme:
        return 0
    if options.check:
        sys.stderr.write(f"{options.readme} is not current; run pdm run acceptance-status\n")
        return 1
    options.readme.write_text(written, encoding="utf-8")
    sys.stdout.write(f"Wrote the status table to {options.readme}.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
