"""Hash-lock the Linux Python 3.14 fixture companion directly from PDM's reviewed runtime."""

from __future__ import annotations

import argparse
import re
import tomllib
from pathlib import Path
from typing import Any

from packaging.markers import Marker, default_environment

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "container/companion-requirements.txt"
GROUPS = {"server", "index", "acceptance", "test"}
ENVIRONMENT = {key: str(value) for key, value in default_environment().items()} | {
    "sys_platform": "linux",
    "platform_system": "Linux",
    "platform_machine": "x86_64",
    "os_name": "posix",
    "python_version": "3.14",
    "python_full_version": "3.14.0",
    "implementation_name": "cpython",
    "platform_python_implementation": "CPython",
}


def _selected(row: dict[str, Any]) -> bool:
    if row["name"] == "nci-si-acceptance" or not GROUPS.intersection(row.get("groups", [])):
        return False
    return not row.get("marker") or Marker(row["marker"]).evaluate(ENVIRONMENT)


def _hashes(rows: list[dict[str, Any]]) -> list[str]:
    hashes = {
        item["hash"]
        for row in rows
        for item in row.get("files", [])
        if item["file"].endswith(".whl")
    }
    if not hashes or any(re.fullmatch(r"sha256:[a-f0-9]{64}", digest) is None for digest in hashes):
        raise ValueError("Companion dependency needs SHA-256 wheel hashes")
    return sorted(hashes)


def _packages(lock: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    packages: dict[str, list[dict[str, Any]]] = {}
    for row in lock["package"]:
        if _selected(row):
            packages.setdefault(row["name"], []).append(row)
    return packages


def render(lock: dict[str, Any]) -> str:
    lines = [
        "# Generated by scripts/companion_lock.py from pdm.lock; do not edit.",
        "# Linux CPython 3.14; fixture runtime only, no embedding model or build tools.",
    ]
    for name, rows in sorted(_packages(lock).items()):
        versions = {row["version"] for row in rows}
        if len(versions) != 1:
            raise ValueError("Conflicting companion dependency versions")
        requirement = f"{name}=={versions.pop()}"
        lines.append(
            " \\\n    ".join([requirement, *(f"--hash={digest}" for digest in _hashes(rows))])
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("write", "check"))
    args = parser.parse_args()
    expected = render(tomllib.loads((ROOT / "pdm.lock").read_text()))
    if args.action == "write":
        LOCK.write_text(expected)
    elif LOCK.read_text() != expected:
        raise ValueError("Companion requirements drifted from pdm.lock; regenerate them")


if __name__ == "__main__":
    main()
