"""Generate the CPU image lock from PDM versions and a Linux pip resolution report."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "container/requirements-amd64.txt"


def versions() -> dict[str, str]:
    packages = tomllib.loads((ROOT / "pdm.lock").read_text())["package"]
    return {
        package["name"]: package["version"]
        for package in packages
        if set(package.get("groups", [])) & {"server", "index", "embeddings"}
    }


def normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def fingerprint() -> str:
    return hashlib.sha256(json.dumps(versions(), sort_keys=True).encode()).hexdigest()


def prepare(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    pins = versions()
    (directory / "constraints.txt").write_text(
        "".join(f"{name}=={version}\n" for name, version in sorted(pins.items()))
    )
    # Only torch comes from this index; all other dependencies resolve against PyPI.
    wheel = f"torch-{pins['torch']}%2Bcpu-cp314-cp314-manylinux_2_28_x86_64.whl"
    (directory / "roots.txt").write_text(
        f"mcp\nnumpy\nsentence-transformers\ntorch @ https://download.pytorch.org/whl/cpu/{wheel}\n"
    )


def render(report: dict) -> str:
    pins = versions()
    lines = ["# Generated by scripts/container_lock.py; do not edit.", f"# PDM: {fingerprint()}"]
    for item in sorted(report["install"], key=lambda item: item["metadata"]["name"].lower()):
        name = normalize(item["metadata"]["name"])
        version = item["metadata"]["version"]
        expected = pins[name] + ("+cpu" if name == "torch" else "")
        if version != expected:
            raise ValueError(f"{name}: resolved {version}, PDM requires {expected}")
        download = item["download_info"]
        digest = download["archive_info"]["hashes"]["sha256"]
        requirement = f"{name}=={version}"
        if name == "torch":
            if not download["url"].startswith("https://download.pytorch.org/whl/cpu/"):
                raise ValueError("torch must come from the CPU wheel index")
            requirement = f"torch @ {download['url']}"
        lines.append(f"{requirement} --hash=sha256:{digest}")
    return "\n".join(lines) + "\n"


def check_requirement(requirement: str, pins: dict[str, str]) -> None:
    if requirement.startswith("torch @ "):
        wheel = f"torch-{pins['torch']}%2Bcpu-cp314-cp314-manylinux_2_28_x86_64.whl"
        if requirement != f"torch @ https://download.pytorch.org/whl/cpu/{wheel}":
            raise ValueError("CPU torch drifted from pdm.lock")
    else:
        name, version = requirement.split("==")
        if pins[name] != version:
            raise ValueError(f"{name} drifted from pdm.lock")


def check() -> None:
    text = LOCK.read_text()
    if f"# PDM: {fingerprint()}\n" not in text:
        raise ValueError("Container lock drifted from pdm.lock; regenerate it")
    pins = versions()
    for line in text.splitlines():
        if line.startswith("#"):
            continue
        requirement, digest = line.split(" --hash=sha256:")
        if not re.fullmatch(r"[a-f0-9]{64}", digest):
            raise ValueError("A dependency has no SHA-256 hash")
        check_requirement(requirement, pins)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("prepare", "write", "check"))
    parser.add_argument("path", nargs="?", type=Path)
    args = parser.parse_args()
    if args.action == "check":
        check()
    elif args.action == "prepare":
        prepare(args.path or ROOT / "tmp/container-lock")
    else:
        LOCK.parent.mkdir(exist_ok=True)
        LOCK.write_text(render(json.loads(args.path.read_text())))


if __name__ == "__main__":
    main()
